FROM ruby:3.0.5

WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN bundle exec jekyll build

EXPOSE 4000

ENTRYPOINT ["bundle", "exec", "jekyll"]
