name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Boon Command
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ github.repository_owner }}/boon:latest
          options: --rm
          run: boon --assert-content schemas/ob_v3p0_achievementcredential_schema.json *.json
