name: Test

on:
  push:
    branches: [ "main" ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if schemas conform to the schemas defined in credentialSchema attribute
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ github.repository_owner }}/boon:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          options: --rm -v ${{ github.workspace }}:/usr/src/myapp
          run: ./check_vc_credential_schemas.sh *json
